INSERT INTO players(name) VALUES ('Jannik Sinner');
INSERT INTO players(name) VALUES ('Novak Djokovic');
INSERT INTO players(name) VALUES ('Carlos Alcaraz');
INSERT INTO players(name) VALUES ('Alexander Zverev');
INSERT INTO players(name) VALUES ('Daniil Medvedev');
INSERT INTO players(name) VALUES ('Andrey Rublev');
INSERT INTO players(name) VALUES ('Hubert Hurkacz');
INSERT INTO players(name) VALUES ('Casper Ruud');
INSERT INTO players(name) VALUES ('Alex de Minaur');
INSERT INTO players(name) VALUES ('Grigor Dimitrov');
INSERT INTO matches (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 6);
INSERT INTO matches (player1, player2, winner) VALUES (1, 3, 3);
INSERT INTO matches (player1, player2, winner) VALUES (2, 5, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 6, 3);
INSERT INTO matches (player1, player2, winner) VALUES (1, 4, 1);
INSERT INTO matches (player1, player2, winner) VALUES (1, 5, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 7, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (4, 7, 4);
INSERT INTO matches (player1, player2, winner) VALUES (4, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (3, 5, 5);
INSERT INTO matches (player1, player2, winner) VALUES (1, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (7, 5, 5);
INSERT INTO matches (player1, player2, winner) VALUES (1, 5, 5);
INSERT INTO matches (player1, player2, winner) VALUES (1, 6, 6);